### ISSUE TITLE
Download APKs from official repositories

### ISSUE THREAD

**Issue by csagan5** [bromite/bromitewebview#2]
The APK should be downloaded from the official Bromite Github releases; if possible the version should be extracted from the Magisk module version.

**Comment by csagan5** [comment]
@alexa-v2 see commit 7518f439eaf4f48d0031d5a4fb8600ee758c3dd3

Would it be possible to extract the version directly from the Magisk module version?

**Comment by androidacy-user** [comment]
It'd require additional logic to handle

Right now my aim is to download the latest, once that's accomplished I may look into it

**Comment by androidacy-user** [comment]
Thanks for the the commit though 👍

Just looked at it

**Comment by csagan5** [comment]
> Thanks for the the commit though

See https://github.com/Magisk-Modules-Repo/bromitewebview/issues/1

**Comment by csagan5** [comment]
> Right now my aim is to download the latest, once that's accomplished I may look into it

This can be done by retrieving the releases via Github API. See https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c for an example; it might be more complicated with Android's shell.
